apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: mysql-service
    app: auth-app
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30003
  selector:
    name: mysql-pod
    app: auth-app