apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    name: mysql-deploy
    app: auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
      app: auth-app
  template:
    metadata:
      name: mysql-pod
      labels:
        name: mysql-pod
        app: auth-app
    spec:
      containers:
      - name: mysqldb
        image: mysql
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "baolong"
          - name: MYSQL_DATABASE
            value: "authdb"