version: 2.1
jobs:
  build_and_test_auth:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            cd src/auth
            pip3 install -r requirements.txt --no-cache-dir
      - run:
          name: Run Tests
          command: |
            coverage run -m pytest
